 
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: chinook_user
      POSTGRES_PASSWORD: chinook_pass
      POSTGRES_DB: chinook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.35.0
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://chinook_user:chinook_pass@postgres:5432/chinook_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  postgres-data:
